### PR TITLE
Fix Double Publish with PublishAsync

### LINKED ISSUE #148: PublishAsync publishes message twice (.netstandard)
Messages published with the `PublishAsync` method are published twice to all subscribes. In addition to this, the callback to indicated that publishing is finished is never invoked. This bug is intruduced by "Add dotnet core test app #132" where the publish mechanism was changed to support .netcore. Both bugs can be checked with the this unit test:
```
        [TestMethod]
        public void PublishAsync_Callback_EventOnce()
        {
            var syncRoot = new object();
            var messageCount = 0;
            var callbackEvent = new ManualResetEvent(false);

            var messenger = UtilityMethods.GetMessenger();
            messenger.Subscribe<TestMessage>(m => { lock (syncRoot) messageCount++; });
            var message = new TestMessage(this);

            messenger.PublishAsync<TestMessage>(message, ar => callbackEvent.Set());

            Assert.IsTrue(callbackEvent.WaitOne(1000));
            Assert.AreEqual(1, messageCount);
        }
```

### PR DESCRIPTION
**Pull request by gillima**
Messages are published twice but the callback is never invoked when using `PublishAsync`.
Fixes #148

### CODE REVIEW

File: src/TinyMessenger/TinyMessenger.cs [hunk 1]
```diff
@@ -802,10 +802,10 @@ where sub.Subscription.ShouldAttemptDelivery(message)
         #else
         private async void PublishAsyncInternal<TMessage>(TMessage message, AsyncCallback callback) where TMessage : class, ITinyMessage
         {
-            Action publishAction = () => { PublishInternal<TMessage>(message); };
-
-            await Task.Run(publishAction.Invoke);
-            PublishInternal<TMessage>(message);
```
Comment (niemyjski) [inline src/TinyMessenger/TinyMessenger.cs:808]: Can we simplify this into something like this? We should keep this simple and Publish Internal doesn't need to be async as it's a synchronous operation and can run inline (the callback can be awaited).

```cs
PublishInternal<TMessage>(message);
// invoke callback here?
```

**Comment by niemyjski** [comment]
Thanks for the PR! I left some comments :)

File: src/TinyMessenger/TinyMessenger.cs (hunk 1 above)
Comment (gillima) [reply src/TinyMessenger/TinyMessenger.cs:808]: You right! Since the `async void` can't be awaited and is asynchronously therefor. I personally don't like `async void` at all but in this case it might make sense to use it for readability and performance reasons.

**Comment by gillima** [comment]
Ups, just got reminded by the compiler that `async void` methods without `await` are running synchronously. Therefor I changed to a non-async void method that starts a not awaited task...

File: src/TinyMessenger/TinyMessenger.cs (hunk 1 above)
Comment (gkarabin) [reply src/TinyMessenger/TinyMessenger.cs:808]: Prior to the mistake in my PR, the original code was async via BeginInvoke (and still is for the not NETSTANDARD case).  As I understand it, BeginInvoke queues to a Thread Pool. The only way to be synchronous is to “join” with the EndInvoke method.

Unless you want to change that aspect of the Publish method, I think something needs to occur to avoid callbacks blocking the caller thread.

https://devblogs.microsoft.com/dotnet/migrating-delegate-begininvoke-calls-for-net-core/

**Comment by gillima** [comment]
>  Awaiting the Task would cause exceptions to be observed

The exception would be "visible" inside the `PublishAsync` method but not for the called of the method. The issue is that you can't await `async void` methods. Without making `PublishAsync` returning a `Task` I don't think there's a way to get the exception outside of `PublishAsync`

**Comment by gkarabin** [comment]
Right. I think that the behavior on your PR matches the behavior prior to #132. #132 was a mess!

File: src/TinyMessenger/TinyMessenger.cs (hunk 1 above)
Comment (gillima) [reply src/TinyMessenger/TinyMessenger.cs:808]: @niemyjski, @gkarabin. Thanks for the quick and good feedback. I've tried to simplify the method as much as possible while keeping the interface. With the current `void` method I don't think there's a simpler way than using `Task.Run` for doing the publishing asynchronously.

Having `async Tasks` with cancellation support for asynchronous methods would be great but the refactoring would exceed the scope of a #148 bugfix for sure.

Comment (niemyjski) [reply src/TinyMessenger/TinyMessenger.cs:808]: Thanks for the link! I think this looks good with the current signature (fire and forget). Are you happy with me merging this pr?

Comment (gkarabin) [reply src/TinyMessenger/TinyMessenger.cs:808]: It looks good to me!

**Comment by niemyjski** [comment]
Merged! Thanks again for the pr! If I could get some help with https://github.com/grumpydev/TinyIoC/issues/136 that would be a massive help for pushing a release with this.
