### PR TITLE
Fix Resolve Issue with Multiple AutoRegister Calls

### LINKED ISSUE #154: TinyIoCResolutionException after multiple calls of AutoRegister
The "Optimization of memory usage" change introduced a bug that will lead to `TinyIoCResolutionException` when `AutoRegister` is called multiple times. The issue can be reproduced by the following unit test:

```
[TestMethod]
public void AutoRegister_Resolve_MultipleCalls()
{
    var container = UtilityMethods.GetContainer();

    container.AutoRegister(new[] { this.GetType().Assembly }, t => typeof(ITestInterface).IsAssignableFrom(t));
    Assert.IsNotNull(container.Resolve<ITestInterface>());
    AssertHelper.ThrowsException<TinyIoCResolutionException>(() => container.Resolve<ITestInterface2>());

    container.AutoRegister(new[] { this.GetType().Assembly }, t => typeof(ITestInterface2).IsAssignableFrom(t));
    Assert.IsNotNull(container.Resolve<ITestInterface>());
    Assert.IsNotNull(container.Resolve<ITestInterface2>());
}

```

### PR DESCRIPTION
**Pull request by gillima**
The static list of ignore-types must not be changed to prevent side effects when resolving types with predicates.
Fixes #154

### CODE REVIEW

File: src/TinyIoC/TinyIoC.cs [hunk 1]
```diff
@@ -3619,19 +3619,10 @@ private bool IsIgnoredAssembly(Assembly assembly)
...
-            }
 
-            for (int i = 0; i < ignoreChecks.Count; i++)
-            {
-                if (ignoreChecks[i](type))
-                    return true;
-            }
-
-            return false;
+            return registrationPredicate != null && !registrationPredicate(type);
```
Comment (niemyjski) [inline src/TinyIoC/TinyIoC.cs:3625]: Do we know the context on why it was checking the registration Predicate first? Can you please request a review from the person who wrote this?

File: src/TinyIoC/TinyIoC.cs [hunk 2]
```diff
@@ -3582,7 +3582,7 @@ where localType.IsAssignableFrom(implementationType)
     }
     
     // TODO - find a better way to remove "system" assemblies from the auto registration
-        private readonly List<Func<Assembly, bool>> ignoredAssemlies = new List<Func<Assembly, bool>>()
+        private static readonly IReadOnlyList<Func<Assembly, bool>> ignoredAssemlies = new List<Func<Assembly, bool>>()
```
Comment (niemyjski) [inline src/TinyIoC/TinyIoC.cs:3585]: I'm not sure how I feel about this being static. Would someone ever have more than one container instance?

Comment (gillima) [reply src/TinyIoC/TinyIoC.cs:3585]: I added `IReadOnlyList` to avoid modifications of the list but then realized my IDE suggests static ;-)
The assembly ignore list will not change if you have multiple containers. It could be written as (static) if's inside `IsIgnoredAssembly` but the list seems to be more elegant. Since the list is identically for all containers and will never change it can be made static to reduce memory consumption.

File: src/TinyIoC/TinyIoC.cs (hunk 1 above)
Comment (gillima) [reply src/TinyIoC/TinyIoC.cs:3625]: I think the intention of @AlexanderMy was to early return if the predicate matches but then he forgot to remove the line that was adding the predicate to the (previous local) list.

Comment (OleksandrMyznikov) [reply src/TinyIoC/TinyIoC.cs:3625]: @gillima is right

**Comment by niemyjski** [comment]
Thanks for the pr!
